# Generated by Django 5.0.6 on 2024-06-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorAcademico',
            fields=[
                ('id_asesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asesor_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id_bibliografia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliografia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BibliografiaAutor',
            fields=[
                ('id_autor', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('anio_publicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bibliografia_autor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_evaluacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'calificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionMateria',
            fields=[
                ('id_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=50)),
                ('nota_obtenida', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'calificacion_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('apellido_estudiante', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'certificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificadoPrograma',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('programa_estudio', models.CharField(max_length=50)),
                ('promedio_calificaciones', models.CharField(max_length=50)),
                ('fecha_emision', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'certificado_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaseHora',
            fields=[
                ('id_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_finalizacion', models.CharField(max_length=50)),
                ('dia_semana', models.CharField(max_length=50)),
                ('aula_virtual', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clase_hora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('creditos', models.CharField(max_length=50)),
                ('plazas_disponibles', models.CharField(max_length=50)),
                ('nivel_academico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=50)),
                ('codigo_curso', models.CharField(max_length=50)),
                ('plan_estudio', models.CharField(max_length=50)),
                ('requisitos_previos', models.CharField(max_length=50)),
                ('instrumentos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'curso_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteCarrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('programa_estudio', models.CharField(max_length=50)),
                ('fecha_inicio', models.CharField(max_length=50)),
                ('fecha_graduacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estudiante_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteEstado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_financiero', models.CharField(max_length=50)),
                ('historial_academico', models.CharField(max_length=50)),
                ('estado_matricula', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estudiante_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCalificacion',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evaluacion_calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id_evaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('comentarios', models.CharField(max_length=50)),
                ('fecha_evaluacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evaluacion_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('participante', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id_eventos_academic', models.IntegerField(primary_key=True, serialize=False)),
                ('temas_tratar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eventos_academicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioClases',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'horario_clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioHorario',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('profesor_responsable', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laboratorio_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioMateriales',
            fields=[
                ('id_materiales', models.IntegerField(primary_key=True, serialize=False)),
                ('asignacion_practica', models.CharField(max_length=50)),
                ('recursos_disponibles', models.CharField(max_length=50)),
                ('herramientas', models.CharField(max_length=50)),
                ('software', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laboratorio_materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LaboratorioVirtual',
            fields=[
                ('id_laboratorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laboratorio_virtual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_pago', models.CharField(max_length=50)),
                ('referencia_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagosMetodo',
            fields=[
                ('id_metodo_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('detalle_transaccion', models.CharField(max_length=50)),
                ('monto', models.CharField(max_length=50)),
                ('fecha_pago', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pagos_metodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDepartamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('curso_obligatorio', models.CharField(max_length=50)),
                ('creditos_requeridos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plan_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id_plan_estudio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('cursos_electivos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plan_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesorHistorial',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50)),
                ('experiencia_laboral', models.CharField(max_length=50)),
                ('historial_educativo', models.CharField(max_length=50)),
                ('cursos_impartidos', models.CharField(max_length=50)),
                ('cargo_trabajo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profesor_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaCarrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=50)),
                ('requisitos_graduacion', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('requisitos_admision', models.CharField(max_length=50)),
                ('nivel_academico', models.CharField(max_length=50)),
                ('curso_obligatorio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programa_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEstudio',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('objetivos_programa', models.CharField(max_length=50)),
                ('competencias_adquiridas', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programa_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaTutoria',
            fields=[
                ('id_tutoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('objetivos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programa_tutoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecursoAdicional',
            fields=[
                ('id_recurso', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('enlace_descarga', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recurso_adicional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecursoMaterial',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=50)),
                ('licencias', models.CharField(max_length=50)),
                ('anio_publicacion', models.CharField(max_length=50)),
                ('tema_relacionado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'recurso_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutoriaPrograma',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('area_enfoque', models.CharField(max_length=50)),
                ('tutor', models.CharField(max_length=50)),
                ('evaluacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tutoria_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoMateriaEstudiantes',
            fields=[
                ('curso_materia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.cursomateria')),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'curso_materia_estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id_materia', models.OneToOneField(db_column='id_materia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.cursomateria')),
            ],
            options={
                'db_table': 'curso_profesor',
                'managed': False,
            },
        ),
    ]
