# Generated by Django 5.0.6 on 2024-06-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True},
        ),
    ]
